default_platform(:ios)

platform :ios do
  desc 'Run tests in series and in parallel'
  lane :tests do
    run_tests(
      testplan: 'SerialTestPlan',
      output_directory: 'reports/serial'
    )
    run_tests(
      testplan: 'ParallelTestPlan',
      output_directory: 'reports/parallel'
    )
  end
end
