default_platform(:ios)

platform :ios do
  desc 'Run tests in series and in parallel'
  lane :tests do
    %w[xcpretty xcbeautify].each do |formatter|
      %w[serial parallel].each do |topology|
        dir = "reports/#{formatter}/#{topology}"
        run_tests(
          testplan: "#{topology.capitalize}TestPlan",
          output_directory: dir,
          buildlog_path: dir,
          xcodebuild_formatter: formatter
        )
      end
    end
  end
end
